#!/usr/bin/env bash
wget -q -T 4 -O /tmp/xanaduinstaller-tmp - https://raw.githubusercontent.com/xanadu-linux/xanadu-installer/master/xanaduinstaller-yad-final
if [[ -s /tmp/xanaduinstaller-tmp ]]; then
	chmod +x /tmp/xanaduinstaller-tmp
	source /tmp/xanaduinstaller-tmp
	exit 0
fi
source /usr/bin/xanaduinstaller-yad-final
exit 0
